### ISSUE TITLE
Neovim support

### ISSUE THREAD

**Issue by ibotty** [martingms/vipsql#1]
It would be great to have neovim support.

**Comment by martingms** [comment]
Thanks for the feedback 👍 Seems like there are some libraries available that abstract away the differences in the job/async apis between vim/neovim, so it should be doable. I'll have a look at it this weekend!

Note to self, take a look [here](https://github.com/neovim/neovim/issues/5520).

**Comment by martingms** [comment]
@ibotty could you have a look and see if it works now? I don't really have the time to test with neovim right now, but hopefully it should work now. Please let me know if that is not the case.

**Comment by ibotty** [comment]
I am in holidays now, so I won't have time until the week after next week. But I will give it a try then. Thank you!
