### ISSUE TITLE
vipsql db password

### ISSUE THREAD

**Issue by SnekCode** [martingms/vipsql#11]
Hello!  Is there a way to send the password though the buffer when prompted?

**Comment by martingms** [comment]
You mean that you connect to the server without a password, and you get prompted by `psql` to input it interactively?
If so, I think using `:VipsqlShell` should do the trick, bound to `<leader>ps` (in normal mode) in the example bindings.

**Comment by SnekCode** [comment]
Ahh yes, that is how I've been using it.  <leader> po to connect follows by a <leader> ps with the password.  Was wondering if there was a way to do this all at once?

**Comment by martingms** [comment]
Ah, I understand.
Your options afaik are either using a `~/.pgpass` [file](https://www.postgresql.org/docs/current/libpq-pgpass.html), the `PGPASSWORD` [env variable](https://www.postgresql.org/docs/current/libpq-envars.html), or perhaps most ergonomic, a `postgresql://user:password@host` [connection URI](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING). To use a connection URI, simply input it to the `<leader>po` prompt!

**Comment by martingms** [comment]
I'm going to close this now, feel free to reopen if that didn't solve your problem!
