### ISSUE TITLE
Output is hidden: could vipsql scroll window?

### ISSUE THREAD

**Issue by pkail** [martingms/vipsql#12]
Thanks for writing this excellent plugin. 
The only issue I can see is that queries appear one after the other, but are not visible.  Would it be possible to modify the code so that the window scrolls down so that the new query result is at the top?

**Comment by martingms** [comment]
Hi, sorry for the late reply! 

I'm not sure I follow, my result buffer automatically scrolls down when new output is available, as seen in the demo here: https://asciinema.org/a/HTc1gAS2gHxaL7yCECvwKUUPs

Are you seeing different behavior?

**Comment by pkail** [comment]
It does that at first, but stops doing so after a while.

**Comment by martingms** [comment]
Hm ok, that's not behavior I'm able to reproduce. Are you able to record an example (through asciinema or something similar), or describe what happens in a bit more detail?

**Comment by pkail** [comment]
I think the problem is actually a result of the mappings I set up.  I'm sorry about that!
In any case, it's an excellent plugin. I am writing a book on PG and will recommend it as the best way to use PG with Vim.

**Comment by martingms** [comment]
> I think the problem is actually a result of the mappings I set up. I'm sorry about that!
> In any case, it's an excellent plugin. I am writing a book on PG and will recommend it as the best way to use PG with Vim.

No problem @pkail, and good luck with the book! I'd love to take a look when it's published :)
