### ISSUE TITLE
Using vipsql to connect to a foreign server. 

### ISSUE THREAD

**Issue by sentientmachine** [martingms/vipsql#3]
I'm using Gentoo Linux.  I have some bluehost webspace that has a postgresql database.  

I know everything is configured properly on the bluehost database side because this command works and drops me into the postgresql terminal: 

```
voyager:el@~ $ psql --host=10.20.30.40 -U my_username -d machines_testing -p 5432
psql (9.5.3, server 8.4.20)
Type "help" for help.
machines_testing=> select 'foo';
 ?column?
----------
 foo
(1 row)
```

However when I use the same command for vipsql, the plugin doesn't create a channel.

    vipsql --host=10.20.30.40 -U my_username -d machines_testing -p 5432

I try to send a command and I get an error: 

```
Error detected while processing function <SNR>3_Send:
line   11:
Attempted send on a closed channel
```

I know that things are okay on the vipsql side because it connects correctly to the local postgresql database with this command:

    vipsql -Upostgres -d postgres

I can send sql commands and run them as expected.

It appears that vipsql is interpreting the bash parameters passed in and interpreting some of them as new files to open.  I've tried putting things in quotes and using all the variations to communicate to vipsql the config options, and all are met with some kind of error.  

Is there a streamlined way for me to specify host, port, username, database and password?  passing it via bash params seems to be problematic. Maybe there's a silly workaround with escapes and quotes?

**Comment by sentientmachine** [comment]
I've found an irritating low-level work-around, it's ugly but maybe helps in diagnosis.  

If I inject the config parameters right into the ~/.vimrc vipsql_psql_cmd parameter like:

    let g:vipsql_psql_cmd = "psql"
    #change to
    let g:vipsql_psql_cmd = "psql --host=10.20.30.40 -U my_username -d machines_testing -p 5432"

Then at the terminal I just type vipsql, and then everything works as expected from here on out.  It's kind of hacky to inject the credentials at this level though.  So with this workaround, we know it's an issue of passing bash params from vipsql straight through to your plugin who passes it to psql.   The question becomes: "Is there a credential system to bypass this weirdness or some kind of dark magic bash incantation to trick vipsql into sending along the parameters.

**Comment by martingms** [comment]
Hey @sentientmachine, thanks for reporting this. What happens if you start vipsql simply like:

```
$ vipsql
```

and enter the params at the prompt?

**Comment by sentientmachine** [comment]
That works, entering the config parameters at the vipsql prompt causes vipsql to treat the config parameters correctly.

    vipsql

    psql .. > 

    psql .. > --host=10.20.30.40 -U my_username -d machines_testing -p 5432

Then I am able to run sql commands as expected.  So looks like this is a second work-around, still it forces me to do typing or pasting which is undesirable.

What I'm looking for is a way to tell vipsql which config parameters to use from the bash terminal without typing or pasting them into vipsql terminal every time. 

It appears that the trouble is line 25 from vipsql.vim:

    let psql_args = (a:0 > 0) ? a:1 : input("psql .. > ")

Which is invoked from line 120: 

    command -nargs=? VipsqlOpenSession call s:OpenSession(<f-args>)

Well there is the issue.  According to the vimscript manual "Argument Handling" from  http://vimdoc.sourceforge.net/htmldoc/map.html#user-commands

specifically you have: 

    -nargs=?    0 or 1 arguments are allowed

So it looks like that's the trouble.  The commands are being mangled and then interpreted as input files and putting everything in quotes causes vipsql to treat the entire thing as a database name which is derp.

**I found a second work around.**  I can specify a psql connection string and cram it all in conninfo string or URI like this: 

    vipsql "postgresql://my_username@my_hostname.com:5432/my_databasename"

**A third work-around**, I can set these environment variables to psql knows what to do:

    PGDATABASE=my_database PGHOST=my_hostname PGPORT=5432 PGUSER=my_user psql

So that answers my question and resolves this issue, work arounds 2 and 3 are satisfactory because I can cram all that into an alias, and I'm off to the races with a single command.

This vipsql stuff is real good, also protip you should take a day and give this one a try:  https://mutelight.org/dbext-the-last-sql-client-youll-ever-need

**Comment by martingms** [comment]
Thanks for looking into this @sentientmachine. I'm glad you find a satisfying workaround, but it definitely sounds like a bug though, so I'll reopen it so that I remember to have a look when I have the time!

And I'll definitely take a look at dbext when I have the time. Don't hesitate in letting me know if there are any specific features you're missing!

**Comment by fiatjaf** [comment]
I've tried to reproduce the error on my machine, but couldn't. Everything worked.

**Comment by martingms** [comment]
Same here :( I'm sorry @sentientmachine, but I can't seem to reproduce this.
