### ISSUE TITLE
When more than two buffers are opened, vipsql outputs to wrong buffer.

### ISSUE THREAD

**Issue by fiatjaf** [martingms/vipsql#6]
I don't know exactly what are the conditions for this to happen, but I was working with the two buffers, vertically separated, one containing my SQL statements and the other the default `__vipsql__` output buffer. I then opened a new one with more SQL statements, again in a vertical split, and issued a vipsql command from it. The output of the command was appended to my previous buffer with my own SQL commands (which happened to be linked to a file on disk).

I don't understand the vim internals, so forgive me.

Anyway, just a minor bug. vipsql is an amazing plugin, it has changed my life.

**Comment by martingms** [comment]
Thanks for the report @fiatjaf, I will try to replicate (and hopefully fix) this weekend!

**Comment by martingms** [comment]
Could you test if 1c536e7 fixed it @fiatjaf ?

**Comment by fiatjaf** [comment]
Thank you, @martingms! Apparently it has fixed it.
