### ISSUE TITLE
Autosave, somehow?

### ISSUE THREAD

**Issue by fiatjaf** [martingms/vipsql#9]
I normally open vipsql over an `.sql` file I already have, then work on it, save, and so on.

In the past days I've lost a bunch of queries I was writing on the `[Scratch]` file because I was dumb and closed it without realizing it wasn't a file I had.

I don't know how to solve this, maybe save `[Scratch]` sessions on `/tmp/` somehow?

**Comment by martingms** [comment]
Are you talking about the `vipsql` bash-function proposed in the README?

**Comment by fiatjaf** [comment]
Yes, I think. The `nofile` thing, I guess.
Ok, this is not part of vipsql and out of scope, I understand.

**Comment by martingms** [comment]
```
vipsql() {
    vim -c 'setlocal ft=sql | VipsqlOpenSession '"$*" $(mktemp -t vipsql.XXXXX)
}
```

How about trying something like this @fiatjaf ?
